### PR TITLE
Remove CHANGELOG.md and bump changelog from release-on-milestone-closed gha

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| QA            | yes

### CODE REVIEW

**Comment by froschdesign** [comment]
@samsonasik 
The changelog file can be removed!

**Comment by samsonasik** [comment]
So "bump changelog"  need to be removed ?

https://github.com/laminas/laminas-zendframework-bridge/blob/13af2502d9bb6f7d33be2de4b51fb68c6cdb476e/.github/workflows/release-on-milestone-closed.yml#L53-L61

**Comment by froschdesign** [comment]
> So "bump changelog" need to be removed ?

I think this must be done for all repositories.

**Comment by samsonasik** [comment]
I removed the changelog file and its bump changelog from the workflow

**Review by Ocramius — APPROVED** [review]

**Pull request merged**
